name: Scala Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: scala-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Eclipse Temurin - JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Test
      run: sbt test
